import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    user: {
        image: null,
        name: null,
        accessToken: null,
        refreshToken: null,
        email: null,
        userId: null,
        role: null
    },
    isAuthenticated: false,
};

const userSlice = createSlice({
    name: 'user',
    initialState,
    reducers: {
        login: (state, action) => {
            // Update the state with user details and set isAuthenticated to true
            state.user = {
                image: action.payload.image,
                name: action.payload.name,
                accessToken: action.payload.accessToken,
                refreshToken: action.payload.refreshToken,
                email: action.payload.email,
                userId: action.payload.userId,
        role: action.payload.role,

            };
            state.isAuthenticated = true;
        },
        logout: (state) => {
            // Reset the state to initial values
            state.user = {
                image: null,
                name: null,
                accessToken: null,
                refreshToken: null,
                email: null,
                userId: null,
                role : null,
            };
            state.isAuthenticated = false;
        }
    }
})

// Export the actions generated by createSlice
export const { login, logout } = userSlice.actions;

// Export the reducer to be used in the store
export default userSlice.reducer;
