import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    user: null,  // Will hold user details when logged in
    isAuthenticated: false,


};

const userSlice = createSlice({
    name: 'user',
    initialState,
    reducers: {
        // Define the login reducer
        login: (state, action) => {
            // Update the state with user details and set isAuthenticated to true
            state.user = action.payload;
            state.isAuthenticated = true;

        },
        // Optionally, you can define a logout reducer
        logout: (state) => {
            // Reset the state to initial values
            state.user = null;
            state.isAuthenticated = false;
        }
        
    }
})


// Export the actions generated by createSlice
export const { login, logout } = userSlice.actions;

// Export the reducer to be used in the store
export default userSlice.reducer;