name: Deploy to Cpanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Cpanel Deploy
    runs-on: ubuntu-latest
    steps:
      - name: get latest code
        uses: actions/checkout@v4
      
      - name: npm install
        run: npm install

      - name: Build React App
        run: npm run build

      - name: sync files with ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: dist/
          server-dir: /

      - name: fart on goats
        run: npm run fart